package com.erp.kernel.navigation.entity;

import com.erp.kernel.ddic.entity.BaseEntity;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;

/**
 * Represents a naming template for generating standardised entity identifiers.
 *
 * <p>Each template defines a pattern for a specific entity type, allowing
 * consistent naming conventions across the system (e.g. document numbers,
 * order references).
 */
@Entity
@Table(name = "nav_naming_template")
public class NamingTemplate extends BaseEntity {

    @Column(name = "entity_type", nullable = false, unique = true, length = 50)
    private String entityType;

    @Column(name = "pattern", nullable = false, length = 255)
    private String pattern;

    @Column(name = "description", length = 500)
    private String description;

    @Column(name = "example", length = 255)
    private String example;

    /**
     * Returns the entity type this template applies to.
     *
     * @return the entity type
     */
    public String getEntityType() {
        return entityType;
    }

    /**
     * Sets the entity type this template applies to.
     *
     * @param entityType the entity type
     */
    public void setEntityType(final String entityType) {
        this.entityType = entityType;
    }

    /**
     * Returns the naming pattern.
     *
     * @return the pattern
     */
    public String getPattern() {
        return pattern;
    }

    /**
     * Sets the naming pattern.
     *
     * @param pattern the pattern
     */
    public void setPattern(final String pattern) {
        this.pattern = pattern;
    }

    /**
     * Returns the template description.
     *
     * @return the description, or {@code null} if not set
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the template description.
     *
     * @param description the description
     */
    public void setDescription(final String description) {
        this.description = description;
    }

    /**
     * Returns an example value generated by this template.
     *
     * @return the example, or {@code null} if not set
     */
    public String getExample() {
        return example;
    }

    /**
     * Sets an example value generated by this template.
     *
     * @param example the example
     */
    public void setExample(final String example) {
        this.example = example;
    }
}
