-- ============================================================================
-- V4: Security, Authentication & User Management Schema
-- Phase 4 — LDAP, RBAC, 2FA, WebAuthn, SSO, Login Policies
-- ============================================================================

-- Users table
CREATE TABLE auth_user (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR(100)  NOT NULL UNIQUE,
    password_hash   VARCHAR(255),
    email           VARCHAR(255)  NOT NULL UNIQUE,
    first_name      VARCHAR(100)  NOT NULL,
    last_name       VARCHAR(100)  NOT NULL,
    display_name    VARCHAR(200),
    active          BOOLEAN       NOT NULL DEFAULT TRUE,
    locked          BOOLEAN       NOT NULL DEFAULT FALSE,
    ldap_dn         VARCHAR(500),
    last_login_at   TIMESTAMP WITH TIME ZONE,
    password_changed_at TIMESTAMP WITH TIME ZONE,
    failed_login_count  INT       NOT NULL DEFAULT 0,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL
);

-- Roles table
CREATE TABLE auth_role (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name       VARCHAR(100)  NOT NULL UNIQUE,
    description     VARCHAR(500),
    active          BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL
);

-- Permissions table
CREATE TABLE auth_permission (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permission_name VARCHAR(100)  NOT NULL UNIQUE,
    description     VARCHAR(500),
    resource        VARCHAR(200)  NOT NULL,
    action          VARCHAR(50)   NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL
);

-- User-Role mapping table
CREATE TABLE auth_user_role (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT        NOT NULL REFERENCES auth_user(id) ON DELETE CASCADE,
    role_id         BIGINT        NOT NULL REFERENCES auth_role(id) ON DELETE CASCADE,
    assigned_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    UNIQUE(user_id, role_id)
);

-- Role-Permission mapping table
CREATE TABLE auth_role_permission (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id         BIGINT        NOT NULL REFERENCES auth_role(id) ON DELETE CASCADE,
    permission_id   BIGINT        NOT NULL REFERENCES auth_permission(id) ON DELETE CASCADE,
    UNIQUE(role_id, permission_id)
);

-- Authorization objects table (SAP-style)
CREATE TABLE auth_authorization_object (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    object_name     VARCHAR(100)  NOT NULL UNIQUE,
    object_class    VARCHAR(100)  NOT NULL,
    description     VARCHAR(500),
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL
);

-- MFA configuration table
CREATE TABLE auth_mfa_config (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT        NOT NULL REFERENCES auth_user(id) ON DELETE CASCADE,
    mfa_type        VARCHAR(20)   NOT NULL,
    secret_key      VARCHAR(500),
    enabled         BOOLEAN       NOT NULL DEFAULT FALSE,
    verified        BOOLEAN       NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    UNIQUE(user_id, mfa_type)
);

-- WebAuthn credentials table
CREATE TABLE auth_webauthn_credential (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT        NOT NULL REFERENCES auth_user(id) ON DELETE CASCADE,
    credential_id   VARCHAR(500)  NOT NULL UNIQUE,
    public_key      VARCHAR(2000) NOT NULL,
    credential_name VARCHAR(200),
    sign_count      BIGINT        NOT NULL DEFAULT 0,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL
);

-- Login policy table
CREATE TABLE auth_login_policy (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_name             VARCHAR(100)  NOT NULL UNIQUE,
    description             VARCHAR(500),
    min_password_length     INT           NOT NULL DEFAULT 8,
    require_uppercase       BOOLEAN       NOT NULL DEFAULT TRUE,
    require_lowercase       BOOLEAN       NOT NULL DEFAULT TRUE,
    require_digit           BOOLEAN       NOT NULL DEFAULT TRUE,
    require_special_char    BOOLEAN       NOT NULL DEFAULT TRUE,
    password_expiry_days    INT           NOT NULL DEFAULT 90,
    max_failed_attempts     INT           NOT NULL DEFAULT 5,
    lockout_duration_minutes INT          NOT NULL DEFAULT 30,
    session_timeout_minutes INT           NOT NULL DEFAULT 480,
    enforce_mfa             BOOLEAN       NOT NULL DEFAULT FALSE,
    active                  BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at              TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at              TIMESTAMP WITH TIME ZONE NOT NULL
);

-- Login attempt tracking table
CREATE TABLE auth_login_attempt (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR(100)  NOT NULL,
    success         BOOLEAN       NOT NULL,
    ip_address      VARCHAR(45),
    user_agent      VARCHAR(500),
    failure_reason  VARCHAR(200),
    attempted_at    TIMESTAMP WITH TIME ZONE NOT NULL
);

-- Indexes for performance
CREATE INDEX idx_auth_user_username ON auth_user(username);
CREATE INDEX idx_auth_user_email ON auth_user(email);
CREATE INDEX idx_auth_user_role_user_id ON auth_user_role(user_id);
CREATE INDEX idx_auth_user_role_role_id ON auth_user_role(role_id);
CREATE INDEX idx_auth_role_permission_role_id ON auth_role_permission(role_id);
CREATE INDEX idx_auth_mfa_config_user_id ON auth_mfa_config(user_id);
CREATE INDEX idx_auth_webauthn_user_id ON auth_webauthn_credential(user_id);
CREATE INDEX idx_auth_login_attempt_username ON auth_login_attempt(username);
CREATE INDEX idx_auth_login_attempt_attempted_at ON auth_login_attempt(attempted_at);
