-- ============================================================================
-- V6: Presentation Layer & Navigation Schema
-- Phase 6 — Theming, T-Code Navigation, Naming Templates, Screens,
--           Favourites, Recent History, User Preferences
-- ============================================================================

-- Themes
CREATE TABLE nav_theme (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    theme_name      VARCHAR(100) NOT NULL UNIQUE,
    description     VARCHAR(500),
    primary_color   VARCHAR(7) NOT NULL,
    secondary_color VARCHAR(7) NOT NULL,
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    is_default      BOOLEAN NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL
);

-- T-Code definitions
CREATE TABLE nav_tcode (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            VARCHAR(20) NOT NULL UNIQUE,
    description     VARCHAR(500) NOT NULL,
    module          VARCHAR(50) NOT NULL,
    route           VARCHAR(500) NOT NULL,
    icon            VARCHAR(100),
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL
);

-- Naming templates
CREATE TABLE nav_naming_template (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type     VARCHAR(50) NOT NULL UNIQUE,
    pattern         VARCHAR(255) NOT NULL,
    description     VARCHAR(500),
    example         VARCHAR(255),
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL
);

-- Screen definitions
CREATE TABLE nav_screen (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    screen_id       VARCHAR(50) NOT NULL UNIQUE,
    title           VARCHAR(200) NOT NULL,
    description     VARCHAR(500),
    module          VARCHAR(50) NOT NULL,
    tcode_id        BIGINT REFERENCES nav_tcode(id),
    screen_type     VARCHAR(50) NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL
);

-- User favourites
CREATE TABLE nav_favourite (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL REFERENCES auth_user(id),
    tcode_id        BIGINT NOT NULL REFERENCES nav_tcode(id),
    sort_order      INT NOT NULL DEFAULT 0,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    UNIQUE (user_id, tcode_id)
);

-- Recent navigation history
CREATE TABLE nav_recent_history (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL REFERENCES auth_user(id),
    tcode_id        BIGINT NOT NULL REFERENCES nav_tcode(id),
    accessed_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_nav_recent_history_user ON nav_recent_history(user_id);
CREATE INDEX idx_nav_recent_history_accessed ON nav_recent_history(accessed_at);

-- User preferences / personalisation
CREATE TABLE nav_user_preference (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL UNIQUE REFERENCES auth_user(id),
    theme_id        BIGINT REFERENCES nav_theme(id),
    locale          VARCHAR(10) NOT NULL DEFAULT 'en',
    date_format     VARCHAR(20) NOT NULL DEFAULT 'yyyy-MM-dd',
    time_format     VARCHAR(20) NOT NULL DEFAULT 'HH:mm:ss',
    items_per_page  INT NOT NULL DEFAULT 20,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL
);
