-- ============================================================================
-- V7: Resilience, Backup & Disaster Recovery Schema
-- Phase 8 — Backup Records, Recovery Points
-- ============================================================================

-- Backup operation metadata
CREATE TABLE backup_records (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    backup_type     VARCHAR(20)   NOT NULL,
    status          VARCHAR(20)   NOT NULL,
    started_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    completed_at    TIMESTAMP WITH TIME ZONE,
    location        VARCHAR(512),
    size_bytes      BIGINT,
    checksum        VARCHAR(128),
    error_message   VARCHAR(1024),
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_backup_records_type    ON backup_records (backup_type);
CREATE INDEX idx_backup_records_status  ON backup_records (status);
CREATE INDEX idx_backup_records_started ON backup_records (started_at);

-- Disaster recovery points (created from verified backups)
CREATE TABLE recovery_points (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    backup_record_id    BIGINT        NOT NULL,
    label               VARCHAR(255)  NOT NULL,
    status              VARCHAR(20)   NOT NULL,
    captured_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    replicated_at       TIMESTAMP WITH TIME ZONE,
    replication_target  VARCHAR(512),
    notes               VARCHAR(1024),
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at          TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_recovery_points_status     ON recovery_points (status);
CREATE INDEX idx_recovery_points_captured   ON recovery_points (captured_at);
CREATE INDEX idx_recovery_points_backup_id  ON recovery_points (backup_record_id);
